services:
  db:
    image: postgres:16
    container_name: koora-postgres
    environment:
      POSTGRES_DB: koora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - koora_pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: koora-app
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/koora
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  koora_pgdata: